export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </PrimeReactProvider>
  )
}
