export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import 'primeflex/primeflex.css';
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <head><link id="app-theme" rel="stylesheet" href="/themes/lara-dark-blue/theme.css" /></head>
        <body>{children}</body>
      </html>
    </PrimeReactProvider>
  )
}
